###### Single layer neural networks:

In [1]:
# import PyTorch
import torch

In [2]:
# create sigmoid activation function
def activation(x):
    return 1/(1+torch.exp(-x))

In [3]:
# Generate some data
torch.manual_seed(7)
#set Features
features=torch.randn((1,5))
#set weights 
weights=torch.randn_like(features)
#set bias
bias=torch.randn((1,1))

Exercise: Calculate the output of the network with input features features, weights weights, and bias bias. Similar to Numpy, PyTorch has a torch.sum() function, as well as a .sum() method on tensors, for taking sums. Use the function activation defined above as the activation function.

In [4]:
#Calculate the output of the network with input features features, weights weights, and bias bias.
y=activation(torch.sum(features*weights)+bias)
print(y)

tensor([[0.1595]])


Exercise: Calculate the output of our little network using matrix multiplication.

In [5]:
#Calculate the output of our little network using matrix multiplication
y=activation(torch.mm(features,weights.view(5,1)+bias))
print(y)

tensor([[0.2154]])


###### Networks Using Matrix Multiplication:

In [6]:
# Generate some data
torch.manual_seed(7)
#set Features
features=torch.randn((1,3))
#Define size of each layer
n_input=features.shape[1] #Number of input units,must match number of input features
n_hidden=2                #Number of hidden units
n_output=1                #Number of output units
#set weights 
#Set weights for inputs to hidden layres
w1=torch.randn(n_input,n_hidden)
#Set weights for hidden layer to output layer
w2=torch.randn(n_hidden,n_output)
#set bias
#Set bias for hidden layer
b1=torch.randn((1,n_hidden))
#Set bias for output layer
b2=torch.randn((1,n_output))

Exercise: Calculate the output for this multi-layer network using the weights W1 & W2, and the biases, B1 & B2.

In [7]:
h=activation(torch.mm(features,w1)+b1)
output=activation(torch.mm(h,w2)+b2)
print(output)

tensor([[0.3171]])


###### Numpy to Torch and back

In [8]:
import numpy as np
a=np.random.rand(4,3)
a

array([[0.37947697, 0.2966143 , 0.40689433],
       [0.4828478 , 0.95548127, 0.22435601],
       [0.39663816, 0.56349107, 0.15246117],
       [0.72952753, 0.35988126, 0.70281526]])

In [9]:
#Create torch tensor from numpy
t=torch.from_numpy(a)
t

tensor([[0.3795, 0.2966, 0.4069],
        [0.4828, 0.9555, 0.2244],
        [0.3966, 0.5635, 0.1525],
        [0.7295, 0.3599, 0.7028]], dtype=torch.float64)

In [10]:
#Back to numpy
t.numpy()

array([[0.37947697, 0.2966143 , 0.40689433],
       [0.4828478 , 0.95548127, 0.22435601],
       [0.39663816, 0.56349107, 0.15246117],
       [0.72952753, 0.35988126, 0.70281526]])

The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will change as well.

In [11]:
t.mul_(2)

tensor([[0.7590, 0.5932, 0.8138],
        [0.9657, 1.9110, 0.4487],
        [0.7933, 1.1270, 0.3049],
        [1.4591, 0.7198, 1.4056]], dtype=torch.float64)

In [12]:
a

array([[0.75895394, 0.59322861, 0.81378865],
       [0.9656956 , 1.91096254, 0.44871202],
       [0.79327633, 1.12698213, 0.30492234],
       [1.45905505, 0.71976252, 1.40563052]])